### PR TITLE
fix: some cosmetic changes in TODO.md

### PR DESCRIPTION
**Pull request by jaymunro**

### CODE REVIEW

**Comment by jaymunro** [comment]
updated the file giving an error on the linting test

**Comment by agittins** [comment]
Thanks for the fixes to the readme!

I have been scratching my head re the version thing. There is a github workflow for release that updates the version numbers in both manifest.json and const.py, so that the copies of those files in the released zip file have the version number in them (see `.github/workflows/release.yaml`).

I don't plan to store the version number in the main branch of the repo because then checkouts of later commits will carry a then-incorrect version number in their files, and automation of releases feels like the right place to manage that. Also I think that a feature of custom components is that if they have a version of 0.0.0 they will override a core integration of the same name (not quite relevant, but I am just trying to go by some established workflow - about which I might be mistaken, however).

I am wondering though if HACS is downloading the zip file or if it's downloading the repo at the commit of the tag instead - the latter would explain how you'd get files with no version number in them. But if you enable "Show beta versions" my understanding is that it will pull directly from the main branch, but maybe the version behaviour is different, too.

I will probably need to push another release before I can test this properly on my system, but there's a bug I want to crush first - hopefully that won't take too long.

If you want to modify your PR to just have the README changes I'll be happy to merge that for now, anyway.

**Comment by jaymunro** [comment]
The reason I updated the version number was when submitting an issue, the form has the following text:
```
## Version of the custom_component

<!-- If you are not using the newest version, download and try that before opening an issue
If you are unsure about the version check the const.py file.
-->
```

So as I wasn't sure of the version # I went to `const.py` to check as instructed and found `0.0.0`

Anyhow, I'm now trying to figure out how to revert that commit in the PR...

**Comment by agittins** [comment]
Yeah, that would have been confusing! Once I've worked out if HACS does something odd with downloading releases (like by checking out the tagged commit instead of the zipped release) I'll update the issue template to make things clearer - thanks for pointing that out.

todo cleanup looks good, thanks!

**Pull request merged**
